### ISSUE TITLE
[Feature request] Don't execute recaptcha if validate() return false

### ISSUE THREAD

**Issue by andrey-hohlov** [MicroDroid/vue-invisible-recaptcha#11]
If form invalid - we don't need to fetch recaptcha token.

What do you think about it?

**Comment by MicroDroid** [comment]
You mean when `validate` function fails? Maybe [this](https://github.com/MicroDroid/vue-invisible-recaptcha/blob/e80d4bf8a014efa6330afc70306c859c0e93e697/src/InvisibleRecaptcha.vue#L87) needs to become:

```JavaScript
if (this.validate && this.validate())
    grecaptcha.execute();
```

That's though if I get your problem correctly. Because if you mean server-side validation then it makes no sense since grecaptcha still should validate then.

**Comment by MicroDroid** [comment]
Can you please check that this actually works and make a pull request? Thanks in advance.

**Comment by andrey-hohlov** [comment]
@MicroDroid It doesn't work, need more changes.

There is an example at the bottom: https://developers.google.com/recaptcha/docs/invisible
To achieve this, need to change template:

```
<template>
  <button :class="computedClass" :type="type" :disabled="!loaded || disabled" :ref="reference" @click="click">
    <div :id="computedId" data-size="invisible"/>
    <slot></slot>
  </button>
</template>
```

and click method:

```javascript
click: function() {
   if (!this.validate || this.validate && this.validate()) {
     grecaptcha.execute(this.widgetId);
   }
}
```

I checked and it works for me with validate prop and without it.

**Comment by MicroDroid** [comment]
Fixed in 0.2.0 which has just been published to NPM.

**Comment by andrey-hohlov** [comment]
@MicroDroid 

> What is this.widgetId though?

From docs:

> grecaptcha.execute(opt_widget_id) | Programatically invoke the reCAPTCHA check. Used if the invisible reCAPTCHA is on a div instead of a button.opt_widget_id  Optional widget ID, defaults to the first widget created if unspecified.

`this.widgetId` defined in render method (result of grecaptcha.render()). Not sure that it needed.

**Comment by MicroDroid** [comment]
Ah, I don't even understand how come I missed checking the `data` thingy for `widgetId`

Anyways, it works perfectly for me even across multiple pages, so I guess it's not important, but you can PR that if you think it's better.

**Comment by andrey-hohlov** [comment]
@MicroDroid 

I test 0.2.0 version and it doesn't work.

Two problems:

1. Missed id for div:
`<div :id="computedId" data-size="invisible"/>`
and it ignores false returning from validate function.

2. It doesn't work if validate function undefined, click method must check it:
```
click: function() {
   if (!this.validate || this.validate && this.validate()) {
     grecaptcha.execute(this.widgetId);
   }
}
```

I created PR with fixes.

**Comment by MicroDroid** [comment]
As far as I understand, the `div` isn't needed, or is it?

I'm trying to avoid that because it's a breaking change to the library, because the point of having the ID on the button is to be able to style the button, and this would probably break things for most users, my projects included.

I'll do some more searching later today to see why `div` is necessary and try to find an alternate solution before falling back to the breaking change.

For the second thing, yeah that's a bug :eyes:

**Comment by andrey-hohlov** [comment]
I think div is needed, look at the example in docs: https://developers.google.com/recaptcha/docs/invisible

Btw, It's an anti-pattern to use id as a selector for styling. But somebody does it.
And it will be breaking change... Looks like you need to release it with 1.0.0 version.

**Comment by MicroDroid** [comment]
@andrey-hohlov Alright, in 6ebdd2f I have made it use two different IDs, one is auto-generated and set for the div so that recaptcha uses, and the `id` prop is set on the button. This way we fixed the thing and also didn't change API.
